# Generated by Django 4.2.2 on 2023-07-01 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_alter_topic_publish_date_alter_topic_created_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='created_time',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='Publish_date',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='is_enable',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='updated_time',
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.topic')),
            ],
        ),
    ]
