# Generated by Django 4.2.2 on 2023-07-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_rename_topic_entry_topicc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topicc',
            new_name='topic',
        ),
    ]
